# POST https://20.73.209.255/echo/resource HTTP/1.1
# Host: 20.73.209.255

POST https://api.rmoreirao.net/echo/resource HTTP/1.1
Host: api.rmoreirao.net
Content-Type: application/json

{
    "vehicleType": "train",
    "maxSpeed": 125,
    "avgSpeed": 90,
    "speedUnit": "mph"
}