### Setup ###
## 1) Create Service Connection "apimDevOpsDev"
## 2) Create Variable Group "deploy" with the following variables:
# DEVOPS_VMPASSWORD
# DEVOPS_PAT
# LOCATION

trigger:
  branches:
    include:
      - main
  paths:
    include:
      - infra/bicep
pool:
  vmImage: ubuntu-latest

variables:
  - group: deploy
  - name: workDir
    value: "$(System.DefaultWorkingDirectory)/ReliableAzureAPIM/infra/bicep"
  - name: gitRepoURL
    value: "https://github.com/rmoreirao/ReliableAzureAPIM.git"

stages:
  - stage: Validate_Preview
    jobs:
      - job: Validate_Preview
        displayName: Preview Changes
        steps:
          - script: git clone $(gitRepoURL)
            displayName: "Clone Repo"
          
          - script: |
              az bicep build --file main.bicep
            name: Lint
            displayName: "Bicep Lint"
            workingDirectory: $(workDir)
          
          - task: AzureCLI@2
            name: Validate
            displayName: Validate Bicep
            inputs:
              azureSubscription: 'apimDevOpsDev'
              workingDirectory: $(workDir)
              scriptType: "bash"
              scriptLocation: "inlineScript"
              inlineScript: |
                az deployment sub what-if \
                  --name $(Build.BuildId) \
                  --template-file main.bicep \
                  --location $(LOCATION) \
                  --parameters main.dev.bicepparam devOpsVmPassword=$(DEVOPS_VMPASSWORD) devOpsPersonalAccessToken=$(DEVOPS_PAT)
                  
          - task: AzureCLI@2
            name: RunWhatIf
            displayName: What-If
            inputs:
              azureSubscription: 'apimDevOpsDev'
              workingDirectory: $(workDir)
              scriptType: "bash"
              scriptLocation: "inlineScript"
              inlineScript: |
                az deployment sub what-if \
                  --name $(Build.BuildId) \
                  --template-file main.bicep \
                  --location $(LOCATION) \
                  --parameters main.dev.bicepparam devOpsVmPassword=$(DEVOPS_VMPASSWORD) devOpsPersonalAccessToken=$(DEVOPS_PAT)

  - stage: Deploy
    jobs:
      - deployment: Deploy
        displayName: Deployment
        environment: production
        strategy:
          runOnce:
            deploy:
              steps:
                - script: git clone $(gitRepoURL)
                  displayName: "Clone Repo"

                - task: AzureCLI@2
                  name: Deployment
                  displayName: Deployment
                  inputs:
                    azureSubscription: 'apimDevOpsDev'
                    workingDirectory: $(workDir)
                    scriptType: "bash"
                    scriptLocation: "inlineScript"
                    inlineScript: |
                      az deployment sub create \
                      --name $(Build.BuildId) \
                      --template-file main.bicep \
                      --location $(LOCATION) \
                      --parameters main.dev.bicepparam devOpsVmPassword=$(DEVOPS_VMPASSWORD) devOpsPersonalAccessToken=$(DEVOPS_PAT)
                    
