trigger:
  branches:
    include:
      - main
  paths:
    include:
      - infra/bicep
pool:
  vmImage: ubuntu-latest

# parameter service connection name
parameters:
  - name: ServiceConnectionName
    type: string
    default: AzureServiceConnection

variables:
  - name: workDir
    value: "$(System.DefaultWorkingDirectory)/ReliableAzureAPIM/infra/bicep"
  - name: gitRepoURL
    value: "https://github.com/rmoreirao/ReliableAzureAPIM.git"

stages:
  - stage: Preview
    jobs:
      - job: Preview
        displayName: Preview Changes
        steps:
          - checkout: $(gitRepoURL)
            clean: true
            
          - task: AzureCLI@2
            name: RunWhatIf
            displayName: What-If
            inputs:
              # param ServiceConnectionName
              azureSubscription: $(ServiceConnectionName)
              workingDirectory: $(workDir)
              scriptType: "bash"
              scriptLocation: "inlineScript"
              inlineScript: |
                az deployment sub what-if \
                  --name $(Build.BuildId) \
                  --template-file main.bicep \
                  --location $(LOCATION) \
                  --parameters main.dev.bicepparam devOpsVmPassword=$(DEVOPS_VMPASSWORD) devOpsPersonalAccessToken=$(DEVOPS_PAT)
              

  - stage: Deploy
    jobs:
      - deployment: Deploy
        displayName: Deployment
        environment: production
        strategy:
          runOnce:
            deploy:
              steps:
                - checkout: $(gitRepoURL)
                  clean: true

                - task: AzureCLI@2
                  name: Deployment
                  displayName: Deployment
                  inputs:
                    azureSubscription: $(ServiceConnectionName)
                    scriptType: "bash"
                    scriptLocation: "inlineScript"
                    inlineScript: |
                      az deployment sub create \
                      --name $(Build.BuildId) \
                      --template-file main.bicep \
                      --location $(LOCATION) \
                      --parameters main.dev.bicepparam devOpsVmPassword=$(DEVOPS_VMPASSWORD) devOpsPersonalAccessToken=$(DEVOPS_PAT)
                    workingDirectory: $(workDir)
